config/routes.rb
UrbanEphemera::Application.routes.draw do

  root to: "authentications#new"
  
  get "users" => "users#index"
  get "users/new" => "users#new"
  get "users/:id" => "users#show"

  get "authentications" => "authentications#index"
  get "authentications/new" => "authentications#new"

  get "stores/map" => "stores#map"

  post "authentications" => "authentications#create"
  post "users" => "users#create"
  patch "reviews/:id" => "reviews#update", as: "review"

  delete "authentications/:id" => "authentications#destroy"
  delete "reviews/:id" => "reviews#destroy"

  resources :stores do
    resources :reviews
  end

  

end

app/models/review.rb
class Review
  include Mongoid::Document

  field :rating, type: Float
  field :body, type: String

  belongs_to :user
  belongs_to :store

end

app/models/store.rb
class Store
  include Mongoid::Document

  field :name, type: String
  field :specialty, type: String
  field :avg_rating, type: Float, default: 0
  field :number_reviews, type: Integer, default: 0
  field :street, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: Integer
  field :phone_number, type: Integer
  field :email, type: String
  field :website, type: String

  has_many :reviews

end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document

  attr_accessor :password, :password_confirmation

  field :number_reviews, type: Integer, default: 0

  # for confirmation
  field :username, type: String
  field :salt, type: String
  field	:hashed_password, type: String

  # has_many :reviews, autosave: true
  has_many :reviews

  before_save :hash_password
  validates :username, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true

  def authenticate(password)
    self.hashed_password == 
    BCrypt::Engine.hash_secret(password, self.salt)
  end

  private

  def hash_password
  	if password.present?
  		self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret(password, self.salt)
      password = password_confirmation = nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def authenticate_user
    redirect_to authentications_url unless current_user
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	before_action :authenticate_user, only: [:destroy]

  def new
    # session[:user_id] = User.first.id
    # Are they already logged in?
    if current_user
      redirect_to users_url
    else
      @user = User.new(username: params[:username])
      render :new
    end
  end

 def create
    user = User.where(username: params[:user][:username]).first

    if user
        # authenticate user
        if user.authenticate(params[:user][:password])
          session[:user_id] = user.id
          redirect_to users_url
        else
          flash.now.alert = "Unable to sign you in. Please try again."
          redirect_to users_new_url
        end
    else
      redirect_to users_new_url(username: params[:user][:username])
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to authentications_url, notice: "You signed out."
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
  	@review = Review.new
    @store = Store.find(params[:store_id])
  end

  def create

    @review = Review.new(params[:review].permit(:rating, :body))
    @review.user = current_user
    @review.store = Store.find(params[:store_id])

    # check to see if review already exists
    if Review.where(user: current_user, store: params[:store_id]).exists?

      # redirect to the edit route
      @review = Review.find_by(user: current_user, store: params[:store_id])
      redirect_to :action => "edit", :id => @review._id   
      
    else
      @review.save

      # Set the number of reviews a user has
      current_user.update(number_reviews: current_user.reviews.count)

      # Update number_reviews field in store
      store = Store.find(params[:store_id])
      store.update(number_reviews: store.reviews.count)

      # Get the average rating for a store
      review_array = store.reviews.to_a
      rating_sum = 0
      review_array.each do |review| 
        rating_sum = rating_sum + review.rating
      end
      store.update(avg_rating: rating_sum/store.reviews.count)

      redirect_to :action => "show", :id => @review._id
       
    end
  end

  def edit
    @review = Review.find(params[:id])
    @store = Store.find(params[:store_id])
  end

  def update
    # Grab user's review
    @review = Review.find(params[:id])
    
    # Update review
    if @review.update(params[:review].permit(:rating, :body))
      
      # Update the average rating for a store
      store = Store.find(params[:store_id])
      review_array = store.reviews.to_a
      rating_sum = 0.0
      review_array.each do |review|
         rating_sum = rating_sum + review.rating
      end
      store.update(avg_rating: rating_sum/store.reviews.count)
    
      redirect_to :action => "show", :id => @review._id
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    # Set the number of reviews a user has
    current_user.update(number_reviews: current_user.reviews.count)

    # Update number_reviews field in store
    store = Store.find(params[:store_id])
    store.update(number_reviews: store.reviews.count)

    # Get the average rating for a store
    review_array = store.reviews.to_a
    rating_sum = 0
    review_array.each do |review| 
      rating_sum = rating_sum + review.rating
    end
    store.update(avg_rating: rating_sum/store.reviews.count)

    redirect_to users_path
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  def index
    @stores = Store.all
  end

  def show
  	@store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(params[:store]
                              .permit(
                                :name,
                                :specialty,
                                :street,
                                :city,
                                :state,
                                :zip,
                                :phone_number,
                                :email,
                                :website
                                ))
    if Store.where(name: params[:store][:name]).exists?
      store = Store.find_by(name: params[:store][:name])
      redirect_to :action => 'show', :id => store._id
    else
      @store.save
      redirect_to :action => 'show', :id => @store._id      
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new(username: params[:username])
  end

  def create
  	@user = User.create(params[:user]
                .permit(:username, :password, :password_confirmation))
  	redirect_to authentications_new_url(username: params[:user][:username])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authentications/index.html.erb
<h1>Hello World</h1>

I am the authentications index view!

<%= session[:user_id] %>

app/views/authentications/new.html.erb
<div id="super-container">

<%= form_for @user, {url:"/authentications", method:"post"} do |u| %>

  <div id="controls">
    <form class="form-horizontal" role="form">
      <div id="text-field-container">
        <div class="form-group">
          <div class="col-lg-10">
            <p>
              <%= u.text_field :username, placeholder: 'username' %>
            </p>
          </div>
        </div>
      </div>
      <div id="text-field-container">
        <div class="form-group">
          <div class="col-lg-10">
            <p>
              <%= u.text_field :password, placeholder: 'password' %>
            </p>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
          <p>
            <%= u.submit "Log In" %>
          </p>
        </div>
      </div>
  </form>
  <div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrbanEphemera</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

User id: <%= session[:user_id] %>

</body>
</html>

app/views/reviews/edit.html.erb
<h1>Review already exists!  Update?</h1>

<%= form_for [@store,@review] do |r| %>

<p>
	<%= r.text_field :rating, placeholder: 'Rating' %>
</p>

<p>
	<%= r.text_field :body, placeholder: 'Review' %>
</p>

<p>
	<%= button_to "Update Review", "/reviews/:id", method: :patch %>
</p>

<p>
	<%= button_to "Destroy Review", store_review_path(@store, @review), method: :delete %>
</p>

<% end %>

review id: <%= @review._id %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<% @reviews.each do |review| %>
  <%= review.rating %>
  <%= review.body %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@store, @review] do |r| %>

<p>
	<%= r.text_field :rating, placeholder: 'rating' %>
</p>

<p>
	<%= r.text_field :body, placeholder: 'body' %>
</p>

<p>
	<%= r.submit %>
</p>

<% end %>

app/views/reviews/show.html.erb
<h1>Review#show</h1>

<%= @review.rating %>
<%= @review.body %>
<%= @review.user_id %>
<%= @review.store_id %>

app/views/reviews/update.html.erb
<h1>Updated this yo!</h1>

<%= @review.rating %>
<%= @review.body %>
<%= @review.user_id %>

app/views/stores/index.html.erb
<h1>Stores</h1>

<% @stores.each do |store| %>
  <%= store.name %>
  <%= store.specialty %>
  <%= store.avg_rating %>
  <%= store.number_reviews %>
  <%= store.street %>
  <%= store.city %>
  <%= store.state %>
  <%= store.zip %>
  <%= store.phone_number %>
  <%= store.email %>
  <%= store.website %>
<% end %>

app/views/stores/map.html.erb
<!-- Map script -->
<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAtDgj_w8lRj-Hgg0z0mUVcfRPwlnNcJU0&sensor=false">
</script>
<script type="text/javascript">
  var geocoder;
  var map;

  // Creates map
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var address = "<%=params[:location]%>"
    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var mapOptions = {
      zoom: 8,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
  }

  // The geocoder
  function codeAddress() {
    var address = "<%=params[:location]%>";
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
        var infowindow = new google.maps.InfoWindow({
          content:"<%=current_user.username%> is here!"
        });
        google.maps.event.addListener(marker, 'click', function() {
          infowindow.open(map,marker);
        });
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);

</script>

<%=params[:location]%>
<input type="button" value="Encode" onclick="codeAddress()">

<!-- Holds map -->
<div id="map-canvas"></div>

app/views/stores/new.html.erb
<%= form_for @store do |s| %>
 <div id="super-container-store">
    <div id="controls">
      <form class="form-horizontal" role="form">
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :name, placeholder: "name" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :specialty, placeholder: "specialty" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :street, placeholder: "street" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :city, placeholder: "city" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :state, placeholder: "state" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :zip, placeholder: "zip" %>
              </p>
            </div>
          </div>
        </div>
         <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :phone_number, placeholder: "phone" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :email, placeholder: "email" %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= s.text_field :website, placeholder: "website" %>
              </p>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-offset-2 col-lg-10">
            <p>
              <%= s.submit %>
            </p>
          </div>
        </div>
    </form>
    <div>
  <div>
<% end %>

app/views/stores/show.html.erb
<div id="super-container-store">

  <div id = "info-block">
    <!-- Thumbnail image -->
    <div class="pull-right">
      <img src="/assets/placeholder_icon.png" class="img-thumbnail"> 
    </div>

    <h1><%= @store.name %></h1>

    <div id = "specialty">
      <%= @store.specialty %>
    </div>
    <div id = "rating">
      <label>Rating: </label> <%= @store.avg_rating %> (<%= @store.number_reviews %> ratings)
    </div>
    <br />


    <div id = "address">
      <div id = "street">
        <%= @store.street %>
      </div>
      <div id = "city-state-zip">
        <%= @store.city %>, <%= @store.state %> <%= @store.zip %>
      </div>
    </div>
    <div id="contact-info">
      <div id = "phone">
        <%= @store.phone_number %>
      </div>
      <div id = "email">
        <%= @store.email %>
      </div>
      <div id = "website">
        <%= @store.website %>
      </div>
    </div>
    <div id="block-button">
      <%= button_to "Write Review", new_store_review_url(@store), method: :get %>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div id="super-container">
  <select id="dropdown">
    <option value="books">Books</option>
    <option value="records">Records</option>
    <option value="all">All</option>
  </select>

  <form class="form-inline" role="form" action="../stores/map" method="get">
    <div id="location-container">
      <div id="text-field-container">
        <div class="form-group">
          <p>
           <input type="text" name="location" placeholder="Location">
           <!-- <button type="submit" class="btn btn-default">Submit</button> -->
           <%= button_to "Submit", stores_map_url, method: :get %>
          </p>
        </div>
      </div>
    </div>
  </form>

  <div id="block-button">
    <%= button_to "Add Store", new_store_url, method: :get %>
  </div>
  <p>
    <%= button_to "Log out", "/authentications/_", method: :delete %>
  </p>
</div>

app/views/users/new.html.erb
<%= form_for @user do |u| %>
  <div id="super-container">
    <div id="controls">
      <form class="form-horizontal" role="form">
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= u.label :username, "Username" %>
                <%= u.text_field :username %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= u.label :password, "Password" %>
                <%= u.text_field :password %>
              </p>
            </div>
          </div>
        </div>
        <div id="text-field-container">
          <div class="form-group">
            <div class="col-lg-10">
              <p>
                <%= u.label :password_confirmation, "Confirm Password" %>
                <%= u.text_field :password_confirmation %>
              </p>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-offset-2 col-lg-10">
            <p>
              <%= u.submit %>
            </p>
          </div>
        </div>
    </form>
    <div>
  <div>
<% end %>

app/views/users/show.html.erb
<h1>User#show</h1>

<%= @user.username %>
<%= @user.number_reviews %>
<%= @user.salt %>
<%= @user.hashed_password %>